version: '3'

services:
  user-backend:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/yijun/.ssh
      - ..:/opt/yijun/code
    command: ["tail -f /dev/null"]




